"""
task.py
-------
Defines the Task class representing a computational task
generated by a mobile device in the MEC environment.

Project: BTP2CSE054 - Task Offloading Decision System in MEC
Team: Akshat Maurya, Ritik Jaiswal, Priyanshu Singh,
      Vanshika Aggarwal, Ayush Patel
Guide: Dr. Prakhar | IILM University, Greater Noida
"""

import random


class Task:
    """
    Represents a single computational task generated by a mobile device.

    Attributes:
        task_id     : Unique identifier for the task
        data_size   : Amount of data to transmit (in bits)
        cpu_cycles  : Computational complexity (in CPU cycles)
        max_delay   : Maximum tolerable deadline (in seconds)
        task_type   : 'delay_sensitive' or 'compute_intensive'
    """

    TASK_TYPES = ["delay_sensitive", "compute_intensive"]

    def __init__(self, task_id, data_size, cpu_cycles, max_delay, task_type=None):
        self.task_id = task_id
        self.data_size = data_size          # bits
        self.cpu_cycles = cpu_cycles        # cycles
        self.max_delay = max_delay          # seconds
        self.task_type = task_type or random.choice(self.TASK_TYPES)

    @classmethod
    def generate_random(cls, task_id, seed=None):
        """Generate a random task within realistic MEC parameter ranges."""
        if seed is not None:
            random.seed(seed)
        data_size = random.uniform(1e4, 1e6)       # 10KB to 1MB in bits
        cpu_cycles = random.uniform(1e7, 1e9)      # 10M to 1B cycles
        max_delay = random.uniform(0.05, 0.5)      # 50ms to 500ms
        task_type = random.choice(cls.TASK_TYPES)
        return cls(task_id, data_size, cpu_cycles, max_delay, task_type)

    def __repr__(self):
        return (
            f"Task(id={self.task_id}, data={self.data_size/1e3:.1f}KB, "
            f"cycles={self.cpu_cycles/1e6:.1f}M, deadline={self.max_delay*1000:.0f}ms, "
            f"type={self.task_type})"
        )
